logging:
  level:
    root: 'INFO'
    com.challenger: 'DEBUG'
    org.springframework.data.mongodb.core.MongoTemplate: 'DEBUG'

spring:
  datasource:
    platform: postgres
    postgres-host: localhost
    url: jdbc:postgresql://${spring.datasource.postgres-host}:5432/app_account_challenger
    name: app_account_challenger
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    continue-on-error: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: true
    format_sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          show_sql: true
          format_sql: true
  cache.type: redis
  data:
    redis:
      port: 6379
      host: localhost
      repositories:
        enabled: true
      default-manager:
        ttl-in-minutes: 60
app-account-challenger:
  openapi:
    dev-url: http://localhost:8080
    prod-url: http://localhost:8080
  async:
    default:
      thread-max-core-pool-size: 4
      max-pool-size: 4
      queue-capacity: 500